name: 'AbbVie Snyk Scan Action'

on: 
  push:
    branches:
      - main
      - master
      - develop
  #workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    env: 
      RESULTS_FILE: "./results.json"
    steps:    
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        # continue-on-error: false #${{ vars.CONTINUE == 'true' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: "--json-file-output=${{ env.RESULTS_FILE }} --org=${{ vars.ORG_ID }} --project-name=${{ vars.PROJECT_NAME }} --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}"
      - name: Check if any of the priority scores are above set threshold  
        if: ${{ always() }}
        run: |
          if [[ -f $RESULTS_FILE ]]; then
            cat $RESULTS_FILE | jq -e 'any(.runs[].results[].properties.priorityScore | . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo ::error:: Priority Score exceeded; exit 1
          fi
        shell: bash


        
         

