name: Snyk Code Scan
on: 
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: |
            --severity-threshold=high
            --org=${{ vars.SNYKLAB_ORG }}
            --project-name=dale-paul/BenchmarkJava

