name: 'AbbVie Snyk Scan Action'

on: 
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

env: 
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  RESULTS_FILE: "./results.json"
  SBOM_FILE: "./sbom.json"
  SBOM_FORMAT: "cyclonedx1.4+json"  # cyclonedx1.4+json, cyclonedx1.4+xml, cyclonedx1.5+json, cyclonedx1.5+xml, cyclonedx1.6+json, cyclonedx1.6+xml, and spdx2.3+json
  
  
jobs:
  security_scans:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@master
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: ${{ vars.MONITOR_MODE == 'true' }}
        with:
          command: test
          args: > 
            --json-file-output=${{ env.RESULTS_FILE }} 
            --org=${{ vars.ORG_ID }} 
            --project-name=${{ vars.PROJECT_NAME }} 
            --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}

      # Special step because so far the Snyk CLI does not accept the Priority Score threshold so have to use this kludge
      - name: Check if any of the priority scores are above set threshold  
        if: ${{ always() }} 
        continue-on-error: ${{ vars.MONITOR_MODE == 'true' }}
        run: >
          if [[ -f $RESULTS_FILE ]]; then \
            cat $RESULTS_FILE \
              | jq -e -c 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) \
              | not' >/dev/null \
                || echo ::error:: Priority Score exceeded; exit 1
          fi
        shell: bash
      
      - name: Generate SBOM
        uses: snyk/actions/maven@master
        with:
          command: sbom
          args: --format=${{ env.SBOM_FORMAT }} -- > ${{ env.SBOM_FILE }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-scan-artifacts
          path: "*.json"
          


        
         

