name: 'AbbVie Snyk Scan Action'

on: 
  push:
    branches:
      - main
      - master
      - develop
  #workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    env: 
      SNYK_ARGS: "--json-file-output=./results.json --org=${{ vars.ORG_ID }} --project-name=${{ vars.PROJECT_NAME }} --severity-threshold=${{ vars.SEVERITY_THRESHOLD }} "
    steps:    
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: ${{ vars.CONTINUE == 'true' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: ${{ env.SNYK_ARGS }}
      - run: echo "RESULTS_PRESENT=$(echo $(if [[ -f "results.json" ]]; then echo true; else echo false; fi))" >> "$GITHUB_OUTPUT"
      - run: echo "$RESULTS_PRESENT"
      - name: Test Priority Level
        if: ${{ env.RESULTS_PRESENT }} #${{ success() }}
        # fail the scan if any priorty score is above our thereshold
        continue-on-error: false
        run: "cat ./results.json | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded';exit 1"
        shell: bash


        
         

