
on: 
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:        
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: ${{ vars.CONTINUE == 'true' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          json: true
          args: |
            --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}
            --org=${{ vars.ORG_ID }}
            --project-name=${{ vars.PROJECT_NAME }} -- >> $GITHUB_OUTPUT
            --json-file-output=/tmp/results.json
      - name: Check Priority Level
        shell: bash
        run: | 
          $(which cat) /tmp/results.json

        
         

