name: Snyk Code Scan
description: Suggested Github Snyk Action

on: 
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: ${{ vars.CONTINUE }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: |
            --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}
            --org=${{ vars.ORG_ID }}
            --project-name=${{ vars.PROJECT_NAME }}
            --json
            --json-file-output=./results.json
      # - name: Check priority score threshold 

