name: Example workflow for Maven using Snyk
on: 
  push:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:
    
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: |
            --severity-level=high
            --org=${{ vars.SNYKLAB_ORG }}
            --project-name=BenchmarkJava
      - name: Continuously monitor Open Source Software
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          args: |
            --org=${{ vars.SNYKLAB_ORG }}
            --project-name=BenchmarkJava
